### PR TITLE
#216  Stats page for community/protocol 

### PR DESCRIPTION
**Pull request by osaguild**
#### Description of the change
Hi. This is the PR for issue #216. I finally complete adding all charts. Please review and merge my PR!
The charts may be a little difficult to read, but I think the design should be improved in the future.

#### Screenshots
deploy-preview-217--devprotocol netlify app_stats_ (1)

#### Checklist

**I agree to the following :-**

- [x] Added description of the change
- [x] I've read the [contributing guidelines](https://github.com/WebXDAO/devprotocol.xyz/blob/main/CONTRIBUTING.md)
- [x] Search previous suggestions before making a new PR, as yours may be a duplicate.
- [x] I acknowledge that all my contributions will be made under the project's license.

Notes (**optional**): 

<a href="https://gitpod.io/#https://github.com/WebXDAO/devprotocol.xyz/pull/217"></a>

### CODE REVIEW

**Review by vinzvinci — APPROVED** [review]
LGTM 👍

**Comment by vinzvinci** [comment]
Hi @osaguild, thanks for your contributions. Please submit your work here to count your contributions: https://app.dework.xyz/devprotocol/community-builders-1?taskId=6dd1ffe4-b7b6-4ae8-b355-adedb6f0c9a3

**Comment by vinzvinci** [comment]
See this @aggre

**Comment by aggre** [comment]
Super! Of course LGTM!

**Review by vinzvinci — APPROVED** [review]
Pretty awesome! LGTM 👍

**Comment by aggre** [comment]
@osaguild The mainnet chart looks like a cliff, but that is due to bulk migration of MVP users. So, it would make more sense to make the starting point the value of this edge. What do you think?

image

**Comment by osaguild** [comment]
> @osaguild The mainnet chart looks like a cliff, but that is due to bulk migration of MVP users. So, it would make more sense to make the starting point the value of this edge. What do you think?
> 
> image

I agree, I fix it.

**Comment by osaguild** [comment]
Hi @aggre,  I fixed. 
image

**Comment by osaguild** [comment]
@aggre How about PR? let me know if you have any requests. I think the content is out of date and may need to be updated.

**Comment by aggre** [comment]
> @aggre How about PR? let me know if you have any requests. I think the content is out of date and may need to be updated. 

Awwwww sorry I didn't notice it, and this PR is great!

**Comment by vinzvinci** [comment]
> > @aggre How about PR? let me know if you have any requests. I think the content is out of date and may need to be updated.
> 
> Awwwww sorry I didn't notice it, and this PR is great!

Should I merge this now?

**Comment by aggre** [comment]
Yeah its great 👍

**Review by vinzvinci — APPROVED** [review]

**Pull request merged**
